"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const signup_validator_1 = require("../validators/auth/signup.validator");
const Auth_controller_1 = require("../controllers/Auth.controller");
const login_validator_1 = require("../validators/auth/login.validator");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.post('/signup', signup_validator_1.signupValidator, (req, res) => Auth_controller_1.authController.signup(req, res));
router.post('/login', login_validator_1.loginValidator, (req, res) => Auth_controller_1.authController.login(req, res));
router.get('/me', (req, res, next) => (0, auth_middleware_1.authMiddleware)(req, res, next), (req, res) => Auth_controller_1.authController.getUser(req, res));
exports.default = router;
