name: "Check lint, test and build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container: node:20
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog
          DB_PORT: 5432
          DB_HOST: db
          DB_USER: ostgres
          DB_PASSWORD: postgres
          DB_NAME: blog
          JWT: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
    env:
      DB_PORT: 5432
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_NAME: blog
      JWT: secret
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run code checks
        run: npm run lint
      
      - name: Run tests
        run: npm test
  build-and-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    env:
      DB_PORT: 5432
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_NAME: blog
      JWT: secret
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "JWT=${{ secrets.JWT_SECRET }}" >> .env
          echo "DB_PORT=5432" >> .env
      

      - name: ls .env
        run: |
          ls -a
          cat .env
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: izzeddin285/blog-backend:latest
      
      - name: Remove .env file
        run: rm .env
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to Azure server and deploy Docker image with Compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_SERVER_IP }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          script: |
            # Update Docker and Docker Compose
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose

            # Create directory for docker-compose file
            mkdir -p ~/app

            # Download docker-compose.prod.yml from artifact
            if [ -d "~/blog-backend" ]; then
              cd ~/blog-backend
              git pull
            else
              git clone https://github.com/izzeddin62/blog-backend.git
            fi

            # Pull the Docker image from Docker Hub
            sudo docker-compose -f ~/blog-backend/docker-compose.prod.yml pull

            echo "DB_HOST=db" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> ~/blog-backend/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ~/blog-backend/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> ~/blog-backend/.env
            echo "JWT=${{ secrets.JWT_SECRET }}" >> ~/blog-backend/.env
            echo "DB_PORT=5432" >> ~/blog-backend/.env

            # Stop and remove existing containers
            sudo docker-compose -f ~/blog-backend/docker-compose.prod.yml down

            # Start new containers
            sudo docker-compose -f ~/blog-backend/docker-compose.prod.yml up -d